/* Generated by tex3ds */
#pragma once

#define npc_blathers_idx 0
#define npc_booker_idx 1
#define npc_celeste_idx 2
#define npc_copper_idx 3
#define npc_cyrus_idx 4
#define npc_gracie_idx 5
#define npc_harvey_idx 6
#define npc_joan_idx 7
#define npc_kicks_idx 8
#define npc_kk_idx 9
#define npc_leif_idx 10
#define npc_leila_idx 11
#define npc_phineas_idx 12
#define npc_redd_idx 13
#define npc_reese_idx 14
#define npc_shrunk_idx 15
#define npc_sina_idx 16
#define npc_tina_idx 17
#define npc_tomNook_idx 18
#define npc_tt_idx 19
