/* Generated by tex3ds */
#pragma once

#define wwface_0_idx 0
#define wwface_1_idx 1
#define wwface_2_idx 2
#define wwface_3_idx 3
#define wwface_4_idx 4
#define wwface_5_idx 5
#define wwface_6_idx 6
#define wwface_7_idx 7
#define wwface_8_idx 8
#define wwface_9_idx 9
#define wwface_10_idx 10
#define wwface_11_idx 11
#define wwface_12_idx 12
#define wwface_13_idx 13
#define wwface_14_idx 14
#define wwface_15_idx 15
