/* Generated by tex3ds */
#pragma once

#define face_0_idx 0
#define face_1_idx 1
#define face_2_idx 2
#define face_3_idx 3
#define face_4_idx 4
#define face_5_idx 5
#define face_6_idx 6
#define face_7_idx 7
#define face_8_idx 8
#define face_9_idx 9
#define face_10_idx 10
#define face_11_idx 11
#define face_12_idx 12
#define face_13_idx 13
#define face_14_idx 14
#define face_15_idx 15
#define face_16_idx 16
#define face_17_idx 17
#define face_18_idx 18
#define face_19_idx 19
#define face_20_idx 20
#define face_21_idx 21
#define face_22_idx 22
#define face_23_idx 23
