/* Generated by tex3ds */
#pragma once

#define hair_0_idx 0
#define hair_1_idx 1
#define hair_2_idx 2
#define hair_3_idx 3
#define hair_4_idx 4
#define hair_5_idx 5
#define hair_6_idx 6
#define hair_7_idx 7
#define hair_8_idx 8
#define hair_9_idx 9
#define hair_10_idx 10
#define hair_11_idx 11
#define hair_12_idx 12
#define hair_13_idx 13
#define hair_14_idx 14
#define hair_15_idx 15
#define hair_17_idx 16
#define hair_18_idx 17
#define hair_19_idx 18
#define hair_20_idx 19
#define hair_21_idx 20
#define hair_22_idx 21
#define hair_23_idx 22
#define hair_24_idx 23
#define hair_25_idx 24
#define hair_26_idx 25
#define hair_27_idx 26
#define hair_28_idx 27
#define hair_29_idx 28
#define hair_30_idx 29
#define hair_31_idx 30
#define hair_32_idx 31
