/* Generated by tex3ds */
#pragma once

#define hairs_0_idx 0
#define hairs_1_idx 1
#define hairs_2_idx 2
#define hairs_3_idx 3
#define hairs_4_idx 4
#define hairs_5_idx 5
#define hairs_6_idx 6
#define hairs_7_idx 7
#define hairs_8_idx 8
#define hairs_9_idx 9
#define hairs_10_idx 10
#define hairs_11_idx 11
#define hairs_12_idx 12
#define hairs_13_idx 13
#define hairs_14_idx 14
#define hairs_15_idx 15
#define hairs_16_idx 16
#define hairs_17_idx 17
#define hairs_18_idx 18
#define hairs_19_idx 19
#define hairs_20_idx 20
#define hairs_21_idx 21
#define hairs_22_idx 22
#define hairs_23_idx 23
#define hairs_24_idx 24
#define hairs_25_idx 25
#define hairs_26_idx 26
#define hairs_27_idx 27
#define hairs_28_idx 28
#define hairs_29_idx 29
#define hairs_30_idx 30
#define hairs_31_idx 31
#define hairs_32_idx 32
#define hairs_33_idx 33
